# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uIxwtzJjAQvPuaC4WH9EK3vAIImrnMKr
"""
import streamlit as st
import openai

# Configurar a chave da API da OpenAI
openai.api_key = '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'

# Função para obter a resposta da OpenAI GPT-3.5
def obter_resposta_gpt(pergunta):
    response = openai.Completion.create(
        engine="text-davinci-003",
        prompt=f"Pergunta: {pergunta}\nResposta:",
        max_tokens=100
    )
    return response.choices[0].text.strip()

# Configurar a página do Streamlit
st.title("Chatbot com Streamlit e OpenAI")

# Adicionar um campo de texto para a pergunta do usuário
pergunta_usuario = st.text_input("Faça uma pergunta ao chatbot:")

# Verificar se a pergunta foi feita e obter a resposta
if pergunta_usuario:
    resposta_chatbot = obter_resposta_gpt(pergunta_usuario)
    st.text_area("Resposta do Chatbot:", value=resposta_chatbot, height=200, max_chars=None)

# Adicionar uma seção de informações
st.info("Este é um chatbot simples usando Streamlit e OpenAI GPT-3.5.")
